apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: http
  namespace: {{ namespace }}
spec:
  parentRefs:
  - name: gateway
    namespace: gwapi
  hostnames: ["{{ backend_app_name }}.{{ ocp_gwapi_domain }}"]
  rules:
  - backendRefs:
    - name: backend-oidc
      port: 8080
