---

########    Frontend Service    #############

- set_fact:
    aprops: "{{ lookup('template', 'templates/application.properties')  }}"

- name: create {{ application_configmap }} application configmap
  k8s:
    state: present
    name: "{{ application_configmap }}"
    namespace: "{{ namespace }}"
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: "{{ application_configmap }}"
      data:
        application.properties: "{{ aprops }}"

- import_tasks: deploy_from_image.yml

###########################################################
