---

########    Backend-OIDC Service    #############

- set_fact:
    sso_hostname: "{{ sso_name }}-{{ namespace_sso }}.{{ ocp_domain }}"

- name: set env var facts
  set_fact:
    sso_realm_url: "https://{{ sso_hostname }}/realms/{{ sso_realm_id }}"
- debug:
    msg: "sso_url = {{ sso_realm_url }}"
- set_fact:
    aprops: "{{ lookup('template', 'templates/application.properties')  }}"

- name: create {{ application_configmap }} application configmap
  k8s:
    state: present
    name: "{{ application_configmap }}"
    namespace: "{{ namespace }}"
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: "{{ application_configmap }}"
      data:
        application.properties: "{{ aprops }}"

- import_tasks: deploy_from_image.yml

###########################################################
