---

########    Backend-OIDC Service    #############

- name: retrieve sso route
  shell: "{{ openshift_cli }} get route sso -o jsonpath='{.spec.host}' -n {{ namespace_sso }}"
  register: sso_route_cmd

- name: set env var facts
  set_fact:
    sso_realm_url: "https://{{ sso_route_cmd.stdout }}/auth/realms/{{ sso_realm_id }}"
- set_fact:
    aprops: "{{ lookup('template', 'templates/application.properties')  }}"

- name: create {{ application_configmap }} application configmap
  k8s:
    state: present
    name: "{{ application_configmap }}"
    namespace: "{{ namespace }}"
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: "{{ application_configmap }}"
      data:
        application.properties: "{{ aprops }}"

- import_tasks: deploy_from_image.yml

###########################################################
