---

# create project

- name: "Does {{ namespace }} namespace already exist"
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Namespace
    name: "{{ namespace }}" 
  register: nm_present
#- debug:
#    msg: "nm_present = {{ nm_present }}"

- name: create project {{ namespace }}
  when: nm_present.resources | length < 1
  block:
  - k8s:
      state: present
      definition: "{{ lookup('template', 'templates/project.yml') | from_yaml }}"
  
  - name: assign user {{ project_admin }} as project admin in {{ namespace }}
    k8s:
      state: present
      definition: "{{ lookup('template', 'templates/rolebinding.yml') | from_yaml }}"
    when: >
      project_admin is defined and
      project_admin is not none and
      project_admin|trim() != ""

