---

# rhsbo operator
sbo_operator_namespace: openshift-operators
sbo_operator_subscription_template: subscription.yml
sbo_operator_packagemanifest: rh-service-binding-operator
sbo_operator_subscription_name: rh-service-binding-operator
sbo_operator_subscription_channel: stable
sbo_operator_subscription_automatic_installplan_approval: false
sbo_operator_subscription_starting_csv: ""
sbo_operator_csv_prefix: service-binding-operator
