apiVersion: capabilities.3scale.net/v1beta1
kind: Backend
metadata:
  name: {{ backend_name }}
spec:
  metrics:
    hits:
      description: Number of API hits
      friendlyName: Hits
      unit: hit
  name: {{ backend_name }}
  privateBaseURL: {{ backend_url }}
  providerAccountRef:
    name: {{ tenant_name }}-tenant-secret
  systemName: {{ backend_name }}
