version: '3.7'

services:

  openldap:
    container_name: openldap
    image: docker.io/osixia/openldap:1.5.0
    restart: always
    ports:
      - "3389:389"
      - "6636:636"
    command: [--copy-service]
    volumes:
    - ./openldap/ldap-example-users.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/ldap-example-users.ldif:bind
    networks:
      - sso

  psql_sso:
    container_name: psql_sso
    image: registry.redhat.io/rhel8/postgresql-12:1-72.1626836556
    restart: always
    ports:
      - "4432:4432"
    environment:
      PGPORT: 4432
      POSTGRESQL_USER: sso
      POSTGRESQL_PASSWORD: sso
      POSTGRESQL_DATABASE: sso
      POSTGRESQL_MAX_PREPARED_TRANSACTIONS: 10
      SCRIPT_DIR: /opt/sql
    volumes:
      - ./sso/db/sso-psql.conf:/opt/app-root/src/postgresql-cfg/sso-psql.conf:bind
    networks:
      - sso

  sso:
    container_name: sso

    # https://github.com/redhat-na-ssa/keycloak_customizations_quickstart/blob/main/etc/sso/Dockerfile
    image: quay.io/jbride/keycloak:19.0.2-0-psql

    restart: always
    ports:
      - "4443:4443"
      - "4080:4080"
    command: [start-dev]
    environment:

      # Add the following entry in your /etc/hosts:  127.0.0.1  sso.local
      KC_HOSTNAME: sso.local

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB_URL: 'jdbc:postgresql://psql_sso:4432/sso'
      KC_DB_USERNAME: sso
      KC_DB_PASSWORD: sso
      JAVA_OPTS_APPEND: -Dkeycloak.migration.strategy=IGNORE_EXISTING -Dkeycloak.import=/opt/ldaprealm.json
      KC_HTTP_PORT: 4080
      KC_HTTPS_PORT: 4443
    volumes:
      - ./sso/ldaprealm.json:/opt/ldaprealm.json:bind
    depends_on:
      - psql_sso
      - openldap
    networks:
      - sso

  backend-service:
    container_name: backend-service
    image: quay.io/redhat_naps_da/backend-oidc:0.0.2
    restart: always
    ports:
      - "6080:6080"
    environment:
      QUARKUS_HTTP_PORT: 6080
      QUARKUS_HTTP_SSL-PORT: 6443  
    volumes:
    - ./backend-service/application.properties:/deployments/config/application.properties:bind
    depends_on:
      - sso
    networks:
      - sso

  frontend-service:
    container_name: frontend-service
    image: quay.io/redhat_naps_da/frontend-oidc:0.0.4
    restart: always
    ports:
      - "7080:7080"
    environment:
      QUARKUS_HTTP_PORT: 7080
      QUARKUS_HTTP_SSL-PORT: 7443  
    volumes:
    - ./frontend-service/application.properties:/deployments/config/application.properties:bind
    depends_on:
      - backend-service
    networks:
      - sso



  token-inspector:
    container_name: token-inspector
    image: quay.io/jbride/keycloak-token-inspector:0.0.2
    restart: always
    ports:
      - "8000:8000"
    environment:
      KC_URL: 'http://sso.local:4080'
      KC_REALM_ID: ldap-demo
      KC_CLIENT_ID: ldap-app
      SERVICE_URL: 'http://localhost:7080/frontend'
    depends_on:
      - sso
      - frontend-service
    networks:
      - sso

networks:
  default:
    driver: bridge
  sso:
    driver: bridge
