version: '3.7'

services:

  openldap:
    container_name: openldap
    image: docker.io/osixia/openldap:1.5.0
    restart: always
    ports:
      - "3389:389"
      - "6636:636"
    command: [--copy-service]
    volumes:
    - ./openldap/ldap-example-users.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/ldap-example-users.ldif:bind
    networks:
      - sso

  psql_sso:
    container_name: psql_sso
    image: registry.redhat.io/rhel8/postgresql-12:1-72.1626836556
    restart: always
    ports:
      - "4432:4432"
    environment:
      PGPORT: 4432
      POSTGRESQL_USER: sso
      POSTGRESQL_PASSWORD: sso
      POSTGRESQL_DATABASE: sso
      POSTGRESQL_MAX_PREPARED_TRANSACTIONS: 10
      SCRIPT_DIR: /opt/sql
    volumes:
      - ./sso/db/sso-psql.conf:/opt/app-root/src/postgresql-cfg/sso-psql.conf:bind
    networks:
      - sso

  sso:
    container_name: sso
    image: quay.io/jbride/keycloak:17.0.0-psql
    restart: always
    ports:
      - "4443:8443"
      - "4080:8080"
    command: [start-dev]
    environment:
      KEYCLOAK_ADMIN: master
      KEYCLOAK_ADMIN_PASSWORD: master
      KC_DB_URL: 'jdbc:postgresql://psql_sso:4432/sso'
      KC_DB_USERNAME: sso
      KC_DB_PASSWORD: sso
      JAVA_OPTS_APPEND: -Dkeycloak.migration.strategy=IGNORE_EXISTING -Dkeycloak.import=/opt/ldaprealm.json
    volumes:
      - ./sso/ldaprealm.json:/opt/ldaprealm.json:bind
    depends_on:
      - psql_sso
      - openldap
    networks:
      - sso


networks:
  default:
    driver: bridge
  sso:
    driver: bridge
