= token-inspector

. Project creation:
+
-----
$ mvn io.quarkus.platform:quarkus-maven-plugin:2.13.1.Final:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=token-inspector \
    -Dextensions='quinoa'
-----

. Run application in dev mode
+
-----
$ mvn compile quarkus:dev
-----
+
**_NOTE:_**  Quarkus now ships with a Dev UI, which is available in dev mode only at http://localhost:8080/q/dev/.

. Build project and container image (using maven).  Push container image to repo:
+
-----
$ mvn clean package \
     -Dquarkus.container-image.build=true \
     -Dquarkus.container-image.push=true
-----
+
NOTE:  Minified javascript app (built via webpack) can be found at:  `target/quinoa-build/main.js`

. Build container image (using podman) and push container image to repo:
+
-----
$ podman build \
    -f src/main/docker/Dockerfile.jvm \
    -t quay.io/redhat_naps_da/token-inspector:0.0.1 \
    token-inspector
-----

. Manually run a `token-inspector` container:
+
-----
$ podman run -it --rm \
    --name=token-inspector \
    -v ./etc/token-inspector/env.production:/opt/token-inspector/src/main/webui/.env \
    -v ./etc/token-inspector/build_and_start.sh:/opt/token-inspector/build_and_start.sh \
    -p 5080:5080 \
    -e QUARKUS_HTTP_PORT=5080 \
    -e QUARKUS_HTTP_SSL-PORT=5443 \
    quay.io/redhat_naps_da/token-inspector:0.0.1
-----

== Related Guides

- Quinoa (link:https://quarkiverse.github.io/quarkiverse-docs/quarkus-quinoa/dev/index.html[Guide]):
+
Quinoa is a Quarkus extension which eases the development, the build and serving single page apps or web components (built with NodeJS: React, Angular, Vue, Lit, …) alongside other Quarkus services (REST, GraphQL, Security, Events, ...).
+
Live code the backend and frontend together with close to no configuration. When enabled in development mode, Quinoa will start the UI live coding server provided by the target framework and forward relevant requests to it. In production mode, Quinoa will run the build and process the generated files to serve them at runtime.

