= token-inspector Project

. Project creation:
+
-----
$ mvn io.quarkus.platform:quarkus-maven-plugin:2.13.1.Final:create     -DprojectGroupId=org.acme     -DprojectArtifactId=token-inspector     -Dextensions='quinoa'
-----

. Build project and container image (using maven).  Push container image to repo:
+
-----
$ mvn clean package \
     -Dquarkus.container-image.build=true \
     -Dquarkus.container-image.push=true
-----
+
NOTE:  Minified javascript app (built via webpack) can be found at:  target/quinoa-build/main.js

. Build container image (using podman) and push container image to repo:
+
-----
$ podman build -f src/main/docker/Dockerfile.jvm -t quay.io/redhat_naps_da/token-inspector:0.0.1 token-inspector
-----

. Manually run a token-inspector container:
+
-----
$ podman run -it --rm \
    --name=token-inspector \
    -v ./etc/token-inspector/env.production:/opt/token-inspector/src/main/webui/.env \
    -v ./etc/token-inspector/build_and_start.sh:/opt/token-inspector/build_and_start.sh \
    -p 5080:5080 \
    -e QUARKUS_HTTP_PORT=5080 \
    -e QUARKUS_HTTP_SSL-PORT=5443 \
    quay.io/redhat_naps_da/token-inspector:0.0.1
-----

This project uses Quarkus, the Supersonic Subatomic Java Framework.

If you want to learn more about Quarkus, please visit its website: https://quarkus.io/ .

## Running the application in dev mode

You can run your application in dev mode that enables live coding using:
```shell script
./mvnw compile quarkus:dev
```

> **_NOTE:_**  Quarkus now ships with a Dev UI, which is available in dev mode only at http://localhost:8080/q/dev/.

## Packaging and running the application

The application can be packaged using:
```shell script
./mvnw package
```
It produces the `quarkus-run.jar` file in the `target/quarkus-app/` directory.
Be aware that it’s not an _über-jar_ as the dependencies are copied into the `target/quarkus-app/lib/` directory.

The application is now runnable using `java -jar target/quarkus-app/quarkus-run.jar`.

If you want to build an _über-jar_, execute the following command:
```shell script
./mvnw package -Dquarkus.package.type=uber-jar
```

The application, packaged as an _über-jar_, is now runnable using `java -jar target/*-runner.jar`.

## Creating a native executable

You can create a native executable using: 
```shell script
./mvnw package -Pnative
```

Or, if you don't have GraalVM installed, you can run the native executable build in a container using: 
```shell script
./mvnw package -Pnative -Dquarkus.native.container-build=true
```

You can then execute your native executable with: `./target/token-inspector-1.0.0-SNAPSHOT-runner`

If you want to learn more about building native executables, please consult https://quarkus.io/guides/maven-tooling.

## Related Guides

- Quinoa ([guide](https://quarkiverse.github.io/quarkiverse-docs/quarkus-quinoa/dev/index.html)): Quinoa is a Quarkus extension which eases the development, the build and serving single page apps or web components (built with NodeJS: React, Angular, Vue, Lit, …) alongside other Quarkus services (REST, GraphQL, Security, Events, ...).

Live code the backend and frontend together with close to no configuration. When enabled in development mode, Quinoa will start the UI live coding server provided by the target framework and forward relevant requests to it. In production mode, Quinoa will run the build and process the generated files to serve them at runtime.


## Provided Code

### Quinoa

This is a tiny webpack app to get started with Quinoa. It generates a quinoa.html page and a script.

[Related guide section...](https://quarkiverse.github.io/quarkiverse-docs/quarkus-quinoa/dev/index.html)

