cat <<EOF
apiVersion: maistra.io/v1
kind: ServiceMeshExtension
metadata:
 labels:
   app: ''
 name: threescale-wasm-extension
spec:
 config:
   api: v1
   backend:
     extensions:
       - no_body
     name: backend
     upstream:
       name: >-
         outbound|443||$API_MGMT_BACKEND_HOST
       timeout: 5000
       url: 'https://$API_MGMT_BACKEND_HOST'
   services:
     - authorities:
         - '*'
       id: '$API_SERVICE_ID'
       credentials:
         app_id:
           - filter:
               path:
                 - envoy.filters.http.jwt_authn
                 - "0"
             keys:
               - azp
               - aud
             ops:
               - take:
                   head: 1
       mapping_rules:
         - method: GET
           pattern: /
           usages:
             - delta: 1
               name: hits
       token: $API_SERVICE_TOKEN
   system:
     name: system
     token: $TENANT_ACCESS_TOKEN
     upstream:
       name: >-
         outbound|443||$TENANT_ADMIN_HOST
       timeout: 5000
       url: 'https://$TENANT_ADMIN_HOST'
 image: 'quay.io/3scale/threescale-wasm-auth:qe'
 phase: PostAuthZ
 priority: 100
 workloadSelector:
   labels:
     app: frontend
EOF
