apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
 labels:
   app: ''
 name: system-entry-apimgr-tenant-provider
spec:
 hosts:
   - %TENANT_ADMIN_HOST%
 location: MESH_EXTERNAL
 ports:
   - name: https
     number: 443
     protocol: HTTPS
 resolution: DNS
