---

- name: Deploy all quickstart resources
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true
  vars_files:
    - group_vars/all.yml
  vars:
    ACTION: install

  tasks:
  - include: tasks/ldap.yml
  - include: tasks/sso.yml
#  - include: tasks/backend.yml
#  - include: tasks/frontend.yml
#  - include: tasks/token-inspector.yml
