---

- name: Deploy token-inspector
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true
  vars_files:
    - group_vars/all.yml

  tasks:
    - include: tasks/token-inspector.yml
