---

- name: "delete product {{ api_product_name }}"
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ api_product_name }}"
    namespace: "{{ apimanager_namespace }}"
    kind: product


- name: "delete backend {{ backend_name }}"
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ backend_name }}"
    namespace: "{{ apimanager_namespace }}"
    kind: backend


- name: "delete tenant {{ tenant_name }}"
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ tenant_name }}"
    namespace: "{{ apimanager_namespace }}"
    kind: tenant
  when: delete_tenant|bool == true

- name: "delete tenant secret {{ tenant_name }}-admin-passwd-secret"
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ tenant_name }}-admin-passwd-secret"
    namespace: "{{ apimanager_namespace }}"
    kind: secret
  when: delete_tenant|bool == true

- name: "delete tenant secret {{ tenant_name }}-generated-secret"
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ tenant_name }}-generated-secret"
    namespace: "{{ apimanager_namespace }}"
    kind: secret
  when: delete_tenant|bool == true

- name: "delete tenant secret {{ tenant_access_token_secret }}"
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ tenant_access_token_secret }}"
    namespace: "{{ apimanager_namespace }}"
    kind: secret
  when: delete_tenant|bool == true
