kind: APIcast
apiVersion: apps.3scale.net/v1alpha1
metadata:
  name: {{ prod_apicast_name }}
  namespace: {{ apigw_namespace }}
spec:
  adminPortalCredentialsRef:
    name: {{ apicast_secret }}
  exposedHost:
    host: {{ apicast_route_hostname }}

    # https://issues.redhat.com/browse/THREESCALE-5485?focusedId=15513205&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-15513205
    tls:
    - {}
  logLevel: {{ gw_log_level }}
  resources:
    requests:
      cpu: '250m'
      memory: '250M'
    limits:
      cpu: '500m'
      memory: '500M'
