apiVersion: capabilities.3scale.net/v1beta1
kind: Backend
metadata:
  name: quarkus-backend
spec:
  metrics:
    hits:
      description: Number of API hits
      friendlyName: Hits
      unit: hit
  name: quarkus-backend
  privateBaseURL: http://backend-oidc.user1-services:8080
  providerAccountRef:
    name: spaceprod-tenant-secret
  systemName: quarkus-backend
