---

- set_fact:
    sso_hostname: "{{ sso_name }}-{{ namespace_sso }}.{{ ocp_domain }}"

- set_fact:
    sso_url: "https://{{ sso_hostname }}"
    frontend_url: "https://frontend-{{ project_name }}.{{ ocp_domain }}/frontend"

- import_tasks: deploy_from_image.yml
