---

- name: delete route
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    kind: route

- name: delete service
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    kind: service

- name: delete deployment config
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    kind: dc

- name: delete imagestream in the {{ namespace }} project
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    kind: imagestream
