---

- set_fact:
    namespace: "{{ project_name }}"
    resources_dir: "{{ resources_base_dir }}/api_gw"
    work_dir_name: api_gw
- include_role:
    name: ../roles/api_gw
  when: >
    ACTION is not defined or
    ACTION is none or
    ACTION|trim() == "" or
    ACTION|trim() == "install"


- include_role:
    name: ../roles/api_gw
    tasks_from: uninstall
  when: >
    ACTION is defined and
    ACTION|trim() == "uninstall"
